name = "LatPhysBandstructuresPlottingPyPlot"
uuid = "66177000-74be-527b-8584-e3f8efd22c83"
authors = ["Jan Attig <jattig@thp.Uni-Koeln.DE>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[deps]
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LatPhysBase = "eec5c15a-e8bd-11e8-0d23-6799ca40c963"
LatPhysLatticeConstruction = "ec4de012-e8d7-11e8-3fed-dfe576d3bbe4"
LatPhysLatticeModification = "84ed28fe-f306-11e8-122d-2faba6147774"
LatPhysLuttingerTisza = "91e24bd6-ff91-11e8-087a-05fe8a0f75ec"
LatPhysPlottingPyPlot = "9928ae8c-f7c6-11e8-0975-05f4db604e41"
LatPhysReciprocal = "7a511e88-ebe4-11e8-1bac-67d16a536c98"
LatPhysReciprocalPlottingPyPlot = "78ec941c-f7c6-11e8-00f5-05526c7d06f4"
LatPhysUnitcellLibrary = "9ab7acfc-e8ca-11e8-283d-b33250f7e765"
LatticePhysics = "53011200-ee7a-11e8-39f1-5f3e57afe4fd"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LatPhysBandstructures = "72414950-169f-5300-802d-f5e080ac9554"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
LatPhysBase = "0.1"
LatPhysLatticeConstruction = "0.1"
LatPhysLatticeModification = "0.1"
LatPhysBandstructures = "0.1"
LatPhysLuttingerTisza = "0.1"
LatPhysReciprocal = "0.1"
LatPhysUnitcellLibrary = "0.1"
LatPhysReciprocalPlottingPyPlot = "0.1"
LatPhysPlottingPyPlot = "0.1"
LatticePhysics = "0.1"
PyPlot = "2.8.2"
LaTeXStrings = "1.0.3"
Reexport = "0.2"
julia = "1"
