name = "LatPhysBandstructuresPlottingPyPlot"
uuid = "66177000-74be-527b-8584-e3f8efd22c83"
authors = ["Jan Attig <jattig@thp.Uni-Koeln.DE>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[deps]
LatPhysBase = "eec5c15a-e8bd-11e8-0d23-6799ca40c963"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LatPhysBandstructures = "72414950-169f-5300-802d-f5e080ac9554"
